# This is the Jolla-modified configdefaults for SFOS

# Enabled checks for the rpmlint to be run
Checks = [
    "AppDataCheck",
    "BinariesCheck",
    "BuildDateCheck",
    'BuildRootCheck',
    "ConfigFilesCheck",
    "DBusPolicyCheck",
    'DuplicatesCheck',
    "DocCheck",
    "FHSCheck",
    "FilesCheck",
    "IconSizesCheck",
    "I18NCheck",
    "LogrotateCheck",
    "PkgConfigCheck",
    "PostCheck",
    "SignatureCheck",
    "SourceCheck",
    "SpecCheck",
    "TagsCheck",
    "ZipCheck",
    # Added for SFOS but disabled for now
    # "DesktopTranslationCheck",
    # "LibraryPolicyCheck",
    # "CheckIconSizes",
    # "CheckStaticLibraries",
    # polkit-default-privs would need to be installed always
    # "CheckPolkitPrivs",
    # "CheckDBUSServices",
    # "CheckAlternativesGhostFiles",
    # "CheckGNOMEMacros",
]

# Various output filters, list of regexp strings eg. "E: .* no-signature"
Filters = [
    '.*source-or-patch-not-compressed.*',
    '.*%mklibname.*',
    '.*no-dependency-on (perl|python)-base.*',
    '.*no-dependency-on locales-.*',
    '.*no-(packager-tag|signature).*',
    '.*incoherent-version-in-name.*',
    '.*invalid-build-requires.*',
    '.*ghost-files-without-postin.*',
    '.*postin-without-ghost-file-creation.*',
    '.*no-major-in-name.*',
    '.*no-provides.*',
    '.*executable-in-library-package.*',
    '.*non-versioned-file-in-library-package.*',
    '.*requires-on-release.*',
    '.*jar-not-indexed.*',
    '.*outside-libdir-files.*',
    '.*-debug(info|source).* no-documentation.*',
    '.*-debuginfo.* /usr/lib/debug/.*',
    '.*-debugsource.* /usr/src/debug/.*',
    '.*non-standard-dir-in-usr libexec.*',
    '^gpg-pubkey:.*',
    '.* doc-file-dependency .* /bin/sh$',
    '.*hardcoded-library-path .*/lib/udev(/|$).*',
    '.*not-standard-release-extension.*',
    '.*explicit-lib-dependency (liberation-fonts|libertas-.*-firmware|libvirt$|.*-(java|python|utils)$).*',
    '.*explicit-lib-dependency (python-.*lib.*|python2-.*lib.*|python3-.*lib.*)$',
    '.*explicit-lib-dependency libreoffice.*$',
    '.*filename-too-long-for-joliet.*',
    '.*symlink-should-be-.*',
    '.*dangling-\S*symlink /usr/share/doc/HTML/\S+/common .+/common$',
    '.*hidden-file-or-dir .*/man5/\.k5login\.5[^/]+$',
    '.*blender.+ (wrong-script-interpreter|non-executable-script) .+/blender/.+\.py.*BPY.*',
# Fedora 12 and newer no longer need a buildroot defined, to have the buildroot cleaned at the beginning
# of %install, and do not need to define a %clean section unless the default is invalid.
    '.*no-cleaning-of-buildroot.*',
    '.*no-buildroot-tag.*',
    '.*no-%clean-section.*',
# Only EL4 needs the files-attr-not-set check, because rpm 4.4 and newer no longer need a %defattr line
# (it automatically provides one).
    '.*files-attr-not-set.*',
# Don't bother with the non-ghost-in-run checks, /var/lock and /var/run are
# symlinks to /run/lock and /run respectively, and /run is a tmpfs
    '.*non-ghost-in-run.*',
# Someone thought it was a good idea to make .desktop files executable. They were wrong.
# Nevertheless, I do not yet control the universe, so we squelch the error here.
    '.*script-without-shebang .*\.desktop$',
# Some files in /etc/ are not meant to be modified by the sysadmin
    '.*non-conffile-in-etc /etc/rpm/.*$',
    '.*non-conffile-in-etc /etc/rc.d/init.d/.*$',
# Fixed in rpm >= 4.7.1
    '.*broken-syntax-in-scriptlet-requires',
# Files that are intentionally not supposed to be readable
# Contains passwords
    '.*non-readable /etc/ovirt-engine/isouploader.conf.*',
# Ignore webservers which are just broken.
    '.*invalid-url .*\.googlecode\.com/.*HTTP Error 404.*',
    '.*invalid-url .*\.jboss\.org/.*HTTP Error 403.*',
    '.*invalid-url .*bitbucket\.org/.*HTTP Error 403.*',
    '.*invalid-url .*github\.com/.*HTTP Error 403.*',
# Don't care about long descriptions on debuginfo packages
# They automatically include the package name and are always
# quite long.
    '.*-debuginfo.* description-line-too-long.*',
# ignore "common" jargon words
# https://bugzilla.redhat.com/show_bug.cgi?id=1424684#c9
    '.*spelling-error.* \b(runtime|Runtime|metadata|cryptographic|multi|linux|filesystem|filesystems|backend|backends|userspace|addon|wayland|Wayland|util|utils|lossless|virtualization|toolkits|libvirtd|crypto|glyphs|GStreamer|http|extensibility|codec|codecs|truetype|scalable|pluggable|pixbuf|Kerberos|customizable|bitstream|tcp|libXss|libs|libc|encodings|GLib|udev|posix|libpng|glapi|gbm|freedesktop|spi|realtime|preprocessor|libaudit|hypervisor|embeddable|distributable|devel|config|cairo|bootloader|adaptors|pragma|passphrase|malloc|libvirt|libmagic|io|datetime|boolean|argparse|py|pinentry|namespace|middleware|lowlevel|libxcb|libudev|libsoup|libgcrypt|libcom|iSCSI|initramfs|GObject|executables|dialogs|checkpolicy|bitmapped|assistive|btrfs|crypttab|defrag|dracut|hostname|luks|mountpoints|netdev|rpmnew|rpmsave|storaged|tss|unlocker)\b.*',
# Ignore 700 dir perms here
    '.*non-standard-dir-perm /etc/.* 700.*',
    '.*non-standard-dir-perm /var/lib/.* 700.*',
# Fedora no longer requires install-info scriptlets
    '.*info-files-without-install-info-postin.*',
    '.*info-files-without-install-info-postun.*',
    '.*postin-without-install-info.*',
# pip 20.2 generates PEP 376 "REQUESTED" marker (empty)
    '.*zero-length .+/site-packages/.+\.dist-info/REQUESTED\b.*',
# Sailfish OS specific changes
    '.*no-manual-page-for-binary.*',
    '.*no-documentation.*',
    '.*non-coherent-filename.*',
    '.*devel-package-with-non-devel-group.*',
    '.*no-group-tag.*',
    '.*non-standard-group.*',
    '.*no-dependency-on locales.*',
    '.*invalid-ldconfig-symlink.*',
    '.*invalid-soname.*',
    '.*library-not-linked-against-libc.*',
    '.*only-non-binary-in-usr-lib.*',
    '.*outside-libdir-files.*',
    '.*unversioned-explicit-provides.*',
    '.*unversioned-explicit-obsoletes.*',
    '.*%ifarch-applied-patch.*',
    '.*conffile-without-noreplace-flag.*',
]
# Whether to use the Enchant spell checker for spell checking
UseEnchant = false
# Whether debug sources are expected to be in separate packages from
# -debuginfo, typically -debugsource.
UseDebugSource = true

# Package scriptlet interpreters
ValidShells = [
    "<lua>",
    "/bin/sh",
    "/bin/bash",
    "/sbin/ldconfig",
    "/usr/bin/perl",
    "/usr/bin/python",
    "/usr/bin/python2",
    "/usr/bin/python3",
]

# Ignore autogenerated parts of version/release number
#
# 1. Ignore possible version suffix added when building from untagged
# revisions.  It is "+<branch-name>.<YYYYMMDDHHMMSS>.<sha1>" optionally followed by
# "+<submodule-name>.<sha1>" for each git submodule with untagged changes. Do
# not simply ignore "+<anything>" as we regularly use "+" in the fixed version
# strings, e.g., v1.2.3+git1.
#
# 2. Completely ignore the release number, which is dynamic
ReleaseExtension = '''\
(\+[^+]+\.[0-9]{14}\.[0-9a-f]{7,10}(\+[^+]+\.[0-9a-f]{7,10})*)?\
-.*$\
'''

# Valid values for the License tag
ValidLicenses = [
    # These are the short names for all of the Fedora approved licenses.
    # The master list is kept here: http://fedoraproject.org/wiki/Licensing
    # Last synced with revision "2.47, July 3, 2018" of that page.
    'AAL',
    'Abstyles',
    'Adobe',
    'ADSL',
    'AFL',
    'Afmparse',
    'AGPLv1',
    'AGPLv3',
    'AGPLv3+',
    'AGPLv3 with exceptions',
    'AMDPLPA',
    'AML',
    'AMPAS BSD',
    'ANTLR-PD',
    'APAFML',
    'App-s2p',
    'APSL 2.0',
    'ARL',
    'Array',
    'Artistic 2.0',
    'Artistic clarified',
    'ASL 1.0',
    'ASL 1.1',
    'ASL 2.0',
    'Bahyph',
    'Barr',
    'Beerware',
    'BeOpen',
    'Bibtex',
    'BitTorrent',
    'Boost',
    'Borceux',
    'BSD',
    'BSD-1-Clause',
    'BSD-2-Clause',
    'BSD-3-Clause',
    'BSD-4-Clause',
    'BSD Protection',
    'BSD with advertising',
    'BSD with attribution',
    'CATOSL',
    'CC0',
    'CeCILL',
    'CeCILL-B',
    'CeCILL-C',
    'CDDL-1.0',
    'CDDL-1.1',
    'CNRI',
    'Condor',
    'Copyright only',
    'CPAL',
    'CPL',
    'CPM',
    'CRC32',
    'Crossword',
    'Crystal Stacker',
    'Cube',
    'diffmark',
    'DMIT',
    'DOC',
    'Dotseqn',
    'DSDP',
    'dvipdfm',
    'DWPL',
    'ECL 1.0',
    'ECL 2.0',
    'eCos',
    'EFL 2.0',
    'eGenix',
    'Entessa',
    'EPICS',
    'EPL-1.0',
    'EPL-2.0',
    'ERPL',
    'EU Datagrid',
    'EUPL 1.1',
    'Eurosym',
    'Fair',
    'FDK-AAC',
    'FSFAP',
    'FSFUL',
    'FSFULLR',
    'FTL',
    'Giftware',
    'GL2PS',
    'Glide',
    'Glulxe',
    'gnuplot',
    'GPL+',
    'GPL+ or Artistic',
    'GPL+ with exceptions',
    'GPLv1',
    'GPLv2 or Artistic',
    'GPLv2+ or Artistic',
    'GPLv2',
    'GPLv2 with exceptions',
    'GPLv2+',
    'GPLv2+ with exceptions',
    'GPLv3',
    'GPLv3 with exceptions',
    'GPLv3+',
    'GPLv3+ with exceptions',
    'HaskellReport',
    'HSRL',
    'IBM',
    'IJG',
    'ImageMagick',
    'iMatix',
    'Imlib2',
    'Inner-Net',
    'Intel ACPI',
    'Interbase',
    'ISC',
    'Jabber',
    'JasPer',
    'JPython',
    'Julius',
    'Knuth',
    'Latex2e',
    'LBNL BSD',
    'Leptonica',
    'LGPLv2',
    'LGPLv2 with exceptions',
    'LGPLv2+',
    'LGPLv2+ or Artistic',
    'LGPLv2+ with exceptions',
    'LGPLv3',
    'LGPLv3 with exceptions',
    'LGPLv3+',
    'LGPLv3+ with exceptions',
    'Lhcyr',
    'libtiff',
    'LLGPL',
    'Logica',
    'LOSLA',
    'LPL',
    'LPPL',
    'MakeIndex',
    'mecab-ipadic',
    'midnight',
    'MirOS',
    'MIT',
    'MITNFA',
    'MIT with advertising',
    'mod_macro',
    'Motosoto',
    'MPLv1.0',
    'MPLv1.1',
    'MPLv2.0',
    'MS-PL',
    'MS-RL',
    'MTLL',
    'Mup',
    'Naumen',
    'NCSA',
    'NetCDF',
    'Netscape',
    'Newmat',
    'Newsletr',
    'NGPL',
    'NISTSL',
    'NLPL',
    'Nmap',
    'Nokia',
    'NOSL',
    'Noweb',
    'OGL',
    'OML',
    'OpenLDAP',
    'OpenPBS',
    'OpenSSL',
    'OReilly',
    'OSL 1.0',
    'OSL 1.1',
    'OSL 2.0',
    'OSL 2.1',
    'OSL 3.0',
    'Par',
    'Phorum',
    'PHP',
    'PlainTeX',
    'Plexus',
    'PostgreSQL',
    'psfrag',
    'psutils',
    'Public Domain',
    'Python',
    'Qhull',
    'QPL',
    'radvd',
    'Rdisc',
    'REX',
    'RiceBSD',
    'Romio',
    'RPSL',
    'RSA',
    'Rsfs',
    'Ruby',
    'Saxpath',
    'Sequence',
    'SCEA',
    'SCRIP',
    'Sendmail',
    'Sleepycat',
    'SISSL',
    'SLIB',
    'SNIA',
    'softSurfer',
    'SPL',
    'STMPL',
    'SWL',
    'TCGL',
    'TCL',
    'Teeworlds',
    'TGPPL',
    'TGPPL with exceptions',
    'Threeparttable',
    'TMate',
    'Tolua',
    'TORQUEv1.1',
    'TOSL',
    'TPDL',
    'TPL',
    'TTWL',
    'Tumbolia',
    'UCAR',
    'UCD',
    'Unicode',
    'Unlicense',
    'Vim',
    'VNLSL',
    'VOSTROM',
    'VSL',
    'W3C',
    'Webmin',
    'Wsuipa',
    'WTFPL',
    'wxWidgets',
    'wxWindows',
    'Xerox',
    'xinetd',
    'xpp',
    'XSkat',
    'YPLv1.1',
    'Zed',
    'Zend',
    'zlib',
    'zlib with acknowledgement',
    'ZPLv1.0',
    'ZPLv2.0',
    'ZPLv2.1',
    # Documentation licenses
    'CDL',
    'FBSDDL',
    'GFDL',
    'IEEE',
    'LDPL',
    'OFSFDL',
    'Open Publication',
    'Public Use',
    'Verbatim',
    # Content licenses
    'CC-BY',
    'CC-BY-ND',
    'CC-BY-SA',
    'DMTF',
    'DSL',
    'EFML',
    'Free Art',
    'GeoGratis',
    'Green OpenMusic',
    'OAL',
    'PDDL-1.0',
    # Font licenses
    'AMS',
    'Arphic',
    'Baekmuk',
    'Bitstream Vera',
    'Charter',
    'DoubleStroke',
    'ec',
    'Elvish',
    'Hershey',
    'HOFL',
    'IPA',
    'Liberation',
    'Lucida',
    'MgOpen',
    'mplus',
    'OFL',
    'PTFL',
    'Punknova',
    'STIX',
    'Utopia',
    'Wadalab',
    'XANO',
    # Others
    'Redistributable, no modification permitted',
    'Freely redistributable without restriction',
    # Sailfish
    'Proprietary',
    'Jolla Proprietary',
]

# Don't exit with an error code
TreatErrorsAsWarnings = true
